export type FileType=
'TEAM_MEMBERS_IMAGES'|'PROJECTS_IMAGES'|'SERVICES_IMAGES'|'CLIENT_IMAGES'|'PROJECT_HERO'|'COMPANY_LOGO';
export type StatusFilter='ALL'|'ONGOING'|'COMPLETED'|'PENDING';
export enum ServiceType {
  ENVIRONMENT = 'ENVIRONMENT',
  AGRICULTURAL = 'AGRICULTURAL',
  PROFESSIONAL = 'PROFESSIONAL',
  GOVERNMENT = 'GOVERNMENT',
  ADVANCED_RESEARCH = 'ADVANCED_RESEARCH'
}
export enum QueryStatus{
  NEW='NEW',
  READ='READ',
  REPLIED='REPLIED'
}