import { Routes } from '@angular/router';
import { HomeComponent } from './features/home/home.component';
import { ProjectsComponent } from './features/projects/projects.component';
import { PortfolioComponent } from './features/portfolio/portfolio.component';
import { ProjectComponent } from './features/projects/project/project.component';
import { ContactUsComponent } from './features/contact-us/contact-us.component';
import { ServicesComponent } from './features/services/services.component';
import { LoginComponent } from './shared/components/login/login.component';
import { LayoutComponent } from './features/admin/layout/layout/layout.component';
import { authGuard } from './guards/auth/auth.guard';
import { roleGuard } from './guards/role/role.guard';

export const routes: Routes = [
    {
        path:'',
        loadComponent:()=>
            import('./features/home/home.component').then(m=>m.HomeComponent)
    },
    {
        path:'projects',
         loadComponent:()=>
            import('./features/projects/projects.component').then(m=>m.ProjectsComponent)
    },
    {
        path:'portfolio',
        loadComponent:()=>
            import('./features/portfolio/portfolio.component').then(m=>m.PortfolioComponent)
    },
   
    {
        path:'contact',
        loadComponent:()=>
            import('./features/contact-us/contact-us.component').then(m=>m.ContactUsComponent)
    },
    {
        path:'services',
        loadComponent:()=>
            import('./features/services/services.component').then(m=>m.ServicesComponent)
    },
    {
        path:'login',
       loadComponent:()=>
        import('./shared/components/login/login.component').then(m=>m.LoginComponent)
    },
    {
        path:'allClients',
        loadComponent:()=>
            import('./features/all-clients/all-clients.component').then(m=>m.AllClientsComponent)
    },
    {
        path:"our_teams",
        loadComponent:()=>
            import('./features/our-teams/our-teams.component').then(m=>m.OurTeamsComponent)
    },
    {
        path:'admin',
        canActivate:[authGuard],
        loadComponent:()=>
            import('./features/admin/layout/layout/layout.component').then(m=>m.LayoutComponent),
        children:[
            {
                path:'dashboard',
                loadComponent:()=>
                    import('./features/admin/pages/dashboard/dashboard.component').then(m=>m.DashboardComponent)
            },
            {
                path:'projects',
                loadComponent:()=>
                    import('./features/admin/pages/projects/all-pojects/all-pojects.component').then(m=>m.AllPojectsComponent)
            },
            {
                path:'projects/add',
                loadComponent:()=>
                    import('./features/admin/pages/projects/add-new-project/add-new-project.component').then(m=>m.AddNewProjectComponent)
            },
            {
                path:'projects/edit/:id',
                loadComponent:()=>
                    import('./features/admin/pages/projects/edit-project/edit-project.component').then(m=>m.EditProjectComponent)
            },
            {
                path:"projects/view/:id",
                loadComponent:()=>
                    import('./features/admin/pages/projects/view-project/view-project.component').then(m=>m.ViewProjectComponent)
            },
            {
                path:'services',
                loadComponent:()=>
                    import('./features/admin/pages/service-pages/all-services/all-services.component').then(m=>m.AllServicesComponent)
            },
            {
                path:'teams',
                loadComponent:()=>
                    import('./features/admin/pages/team-pages/teams/teams.component').then(m=>m.TeamsComponent)
            },
            {
                path:'teams/add',
                loadComponent:()=>
                    import('./features/admin/pages/team-pages/add-team-member/add-team-member.component').then(m=>m.AddTeamMemberComponent)
            },
            {
                path:'teams/edit/:id',
                loadComponent:()=>
                    import('./features/admin/pages/team-pages/edit-team-member/edit-team-member.component').then(m=>m.EditTeamMemberComponent)
            },
            {
                path:"teams/view/:id",
                loadComponent:()=>
                    import('./features/admin/pages/team-pages/view-team-member/view-team-member.component').then(m=>m.ViewTeamMemberComponent)
            },
            {
                path:'users',
                canActivate:[roleGuard],
                loadComponent:()=>
                    import('./features/admin/pages/user-pages/users/users.component').then(m=>m.UsersComponent)
            },
            {
                path:'users/add',
                canActivate:[roleGuard],
                loadComponent:()=>
                    import('./features/admin/pages/user-pages/add-user/add-user.component').then(m=>m.AddUserComponent)
            },
            {
                path:"users/edit/:username",
                canActivate:[roleGuard],
                loadComponent:()=>
                    import('./features/admin/pages/user-pages/edit-user/edit-user.component').then(m=>m.EditUserComponent)
            },
            {
                path:"users/view/:username",
                canActivate:[roleGuard],
                loadComponent:()=>
                    import('./features/admin/pages/user-pages/view-user/view-user.component').then(m=>m.ViewUserComponent)
            },
            {
                path:"clients",
                loadComponent:()=>
                    import('./features/admin/pages/client-pages/all-client/all-client.component').then(m=>m.AllClientComponent)
            },
            {
                path:"clients/add",
                loadComponent:()=>
                    import('./features/admin/pages/client-pages/add-client/add-client.component').then(m=>m.AddClientComponent)
            },
            {
                path:"clients/edit/:id",
                loadComponent:()=>
                    import('./features/admin/pages/client-pages/edit-client/edit-client.component').then(m=>m.EditClientComponent)
            },
            {
                path:"clients/view/:id",
                loadComponent:()=>
                    import('./features/admin/pages/client-pages/view-client/view-client.component').then(m=>m.ViewClientComponent)
            },
            {
                path:'services',
                loadComponent:()=>
                    import('./features/admin/pages/service-pages/all-services/all-services.component').then(m=>m.AllServicesComponent)
            },
            {
                path:"services/add",
                loadComponent:()=>
                    import("./features/admin/pages/service-pages/add-service/add-service.component").then(m=>m.AddServiceComponent)
            },
            {
                path:"services/edit/:id",
                loadComponent:()=>
                    import("./features/admin/pages/service-pages/edit-service/edit-service.component").then(m=>m.EditServiceComponent)
            },
            {
                path:"services/view/:id",
                loadComponent:()=>
                    import("./features/admin/pages/service-pages/view-service/view-service.component").then(m=>m.ViewServiceComponent)
            },
            {
                path:"contacts",
                loadComponent:()=>
                    import("./features/admin/pages/query-pages/all-content-querys/all-content-querys.component").then(m=>m.AllContentQuerysComponent)
            },
            {
                path:"contacts/:id",
                loadComponent:()=>
                    import("./features/admin/pages/query-pages/view-contact-query/view-contact-query.component").then(m=>m.ViewContactQueryComponent)
            },
            {
                path:"contacts/:id/reply",
                loadComponent:()=>
                    import("./features/admin/pages/query-pages/admin-to-reply/admin-to-reply.component").then(m=>m.AdminToReplyComponent)
            },
            {
                path:"settings",
                loadComponent:()=>
                    import("./features/admin/pages/siteSitting-page/add-site-info/add-site-info.component").then(m=>m.AddSiteInfoComponent)
            },
            {
                path:'',
                redirectTo:'dashboard',
                pathMatch:'full'
            }
        ]
    },


    {
        path:"**",
        redirectTo:""
    }
];
